apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-demo
  labels:
    app: angular-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-demo
  template:
    metadata:
      labels:
        app: angular-demo
    spec:
      containers:
      - name: angular-demo
        image: nginxdemos/hello
        ports:
        - containerPort: 80
