apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-echo
  template:
    metadata:
      labels:
        app: hello-echo
    spec:
      containers:
      - name: http-echo
        image: hashicorp/http-echo:0.2.3
        args:
          - "-text=Hello World from Argo CD"
        ports:
        - containerPort: 5678
